name: Build and Deploy to AKS via ArgoCD

on:
  push:
    branches:
      - main  # or your branch

permissions:
  id-token: write  # Required for OIDC login
  contents: write  # To push updated YAML
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- OIDC Login to Azure ---
      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Context
        run: |
          echo "Logged into Azure successfully!"
          az account show --output table

      - name: Set subscription explicitly
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az account show --output table

      # --- Login to ACR ----
      #- name: Login to Azure Container Registry
        #run: |
          #az acr login --name gioakscontainerregistry

      # --- Build and Push Image ---
      - name: Debug Azure info
        run: |
          echo "Client ID: ${client-id:0:5}******"
          echo "Tenant ID: ${tenant_id:0:5}******"
          echo "Subscription ID: ${subscription_id:0:5}******"
          echo "ACR Name: ${{ secrets.ACR_NAME }}"
          echo "Resource Group: $RESOURCE_GROUP"
          echo "Image Name: $IMAGE_NAME"
          az account show
      - name: Build and Push Image
        run: |
          IMAGE_NAME=myapp
          IMAGE_TAG=${{ github.sha }}
          az acr build --registry gioakscontainerregistry -f Apps/Dockerfile . --image myapp:${IMAGE_TAG}
        # --- podman build -t $IMAGE_NAME:$IMAGE_TAG ./Apps ---
        # --- podman push $IMAGE_NAME:$IMAGE_TAG ---
      # --- Update deployment YAML --
      - name: Update deployment image tag
        run: |
          IMAGE_NAME=myapp
          IMAGE_TAG=${{ github.sha }}
          sed -i "s|\(image:\s*\).*|\1$IMAGE_NAME:$IMAGE_TAG|" k8s/base/deployment.yaml

      # --- Commit and push changes back to repo ---
      - name: Commit and Push updated image tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/base/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push